import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { CartProvider } from "@/context/CartContext";
import { DrawerProvider } from "@/context/DrawerContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <DrawerProvider>
          <body className={inter.className}>{children}</body>
        </DrawerProvider>
      </CartProvider>
    </html>
  );
}
